### ISSUE TITLE
Delayed jobs repeats

### ISSUE THREAD

**Issue by brianconnoly** [LearnBoost/kue#449]
Hi there!
Our company uses kue to perform delayed posting in social networks.
We love everything about kue, except one thing. Sometimes jobs run two and even more times.
Our server configuration has a lot of forked workers, that perform jobs execution.
Maybe the reason is my misunderstanding of jobs.promote mechanism.
Should I place this line in every worker or only in master process?

**Comment by jamiter** [comment]
Any updated on this @brianconnoly? I'm having the same issue. Only running one process with one `jobs.promote()` without parameters.

Something I'm doing is changing the max attempts during job execution, which might be the cause. I'm doing this because the error generated by the job should determine if it should be run again or not. Maybe theres a better pattern for this.

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/312
