### ISSUE TITLE
removeOnComplete and job complete event

### ISSUE THREAD

**Issue by laoshanlung** [LearnBoost/kue#507]
In job complete event, sometimes we need to get the job data. However, if `removeOnComplete` is provided when creating a job, `completedJob` in `job complete` event will be `undefined` (since it has already been removed at this point). Is it the desired behaviour?

```
queue.on('job complete', function(id){
  kue.Job.get(id, function(error, completedJob){
    
  });
});
```

**Comment by behrad** [comment]
I think this is the normal result when you are deleting jobs completion. How would you then expect the job data to be exist?
If you need job data after completion, then you should use a manual scheduled remove job procedure :)

**Comment by laoshanlung** [comment]
It's just a bit odd to me, but it is not really a big deal

**Comment by behrad** [comment]
I am here to answer about any unclear points. Please feel free to tell me whats odd about this?

**Comment by laoshanlung** [comment]
In my opinion the ideal situation is to execute all the provided callbacks first, then delete the job afterward. However, taking the current architecture into account, it is not possible to know when a callback is done.

**Comment by behrad** [comment]
This is a blocking behaviour and assumes user has finished with job data when callback returns, however user may process job data asynchronously. I don't think it worth adding an extra done callback to job event handler callbacks for this kind of problem. 

Instead of Kue keeping busy and complicated to know when to remove a job, user tells Kue to when to remove it :)

**Comment by laoshanlung** [comment]
Yes, that makes sense :)
