### ISSUE TITLE
Does consumers in Kue process jobs concurrently so that they maximize use of a multi threaded CPU?

### ISSUE THREAD

**Issue by puttyman** [LearnBoost/kue#541]
Since nodejs apps are single threaded - When consumers process jobs concurrently do they maximize use of a multi threaded CPU?

**Comment by behrad** [comment]
each Kue worker can use multiple open BLPOP connections to pop jobs from redis in a single node.js process to enhance job processing in node's event loop which is called ***Concurrency*** 
However node.js processes won't take more than a single core of you CPU, but `Cluster` module here comes to your help by spawning multiple node.js processes (each contain multiprocessing consumers) which then use multiple cores of your CPU which is called ***Parallelism***
I refer you to the corresponding sections in readme like
https://github.com/LearnBoost/kue#parallel-processing-with-cluster

**Comment by puttyman** [comment]
Thanks for your detailed answer behrad.

**Comment by kenkopelson** [comment]
There are many solutions that allow for multiple threads within Node.js   Just Google it, and you will see there are many libraries that allow you spawn a thread from within a Node.js script.  So, honestly, Kue should be enhanced to use this mechanism so that workers can be done spawned to run jobs.  This would be an ideal solution, where multiple threads are used for CPU intensive work, and the single thread of Node is used to process HTTP requests efficiently.  The best of both worlds!
